		AREA ADDITION,CODE,READONLY
		ENTRY 
		MOV R2,#0x20
		LDR R0,=A
		LDR R1,[R0] 
		ADD R3,R1,R2
		LDR R4,=RESULT
		STR R3,[R4]
STOP 	B STOP
A 		DCD 0x04
		AREA RESULTDATA,DATA,READWRITE
RESULT 	DCD 0x02
		END